# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMSArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('manifest', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonCartridge',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ims.imsarchive',),
        ),
        migrations.CreateModel(
            name='ContentPackage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ims.imsarchive',),
        ),
    ]
